# -*- coding: utf-8 -*-
"""premierleague.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14EO5gYqHho81cN4GCRETSELglU8E34L2

Load data
"""

import pandas as pd

teams = pd.read_csv('/content/premier-league-tables.csv')
data = pd.DataFrame(teams)

"""Data Processing"""

del data["Notes"]

def add_new_col(row):
    if row['Rk'] == 1:
        return 1
    else:
        return 0

data['Won_League'] = data.apply(add_new_col, axis=1)
X = data[['W', 'D', 'GD']]
y = data['Won_League']

"""Data Split"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""Train model"""

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

"""Predict"""

result = model.predict([[30, 1, 80]])
result